services:
  user1:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: UbuntuUser1
    networks:
        custom_net:
          ipv4_address: 172.20.0.5
    stdin_open: true
    tty: true
  attacker:
    build: 
        context: .
        dockerfile: dockerfile.att
    container_name: UbuntuAttacker
    networks:
      custom_net:
        ipv4_address: 172.20.0.6
    stdin_open: true
    tty: true

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
  
    